#if !canImport(ObjectiveC)
import XCTest

extension APIManagerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__APIManagerTests = [
        ("testDeleteRequest", testDeleteRequest),
        ("testGetRequest", testGetRequest),
        ("testHeadRequest", testHeadRequest),
        ("testOptionsRequest", testOptionsRequest),
        ("testPatchRequest", testPatchRequest),
        ("testPostRequest", testPostRequest),
        ("testPutRequest", testPutRequest),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(APIManagerTests.__allTests__APIManagerTests),
    ]
}
#endif
